yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path("", views.index, name="index"),
    path("follow/", views.follow_index, name="follow_index"),
    path("group/<slug:slug>/", views.group_posts, name="group_posts"),
    path("new/", views.new_post, name="new_post"),
    path('<str:username>/', views.profile, name='profile'),
    path('<str:username>/<int:post_id>/', views.post_view, name='post_view'),
    path('<str:username>/<int:post_id>/edit/', views.post_edit,
         name='post_edit'),
    path("<str:username>/<int:post_id>/comment/", views.add_comment,
         name="add_comment"),
    path("<str:username>/follow/", views.profile_follow,
         name="profile_follow"),
    path("<str:username>/unfollow/", views.profile_unfollow,
         name="profile_unfollow"),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("posts.urls", namespace='app_posts')),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = "posts.views.page_not_found"
handler500 = "posts.views.server_error"

# if settings.DEBUG:
#     urlpatterns += static(
#         settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#     urlpatterns += static(
#         settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     import debug_toolbar
#     urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

# urlpatterns += [re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT,}),]
# urlpatterns += [re_path(r'^static/(?P<path>.*)$', serve, {'document_root':settings.STATIC_ROOT}),]

yatube/templates/includes/menu.html
{% if user.is_authenticated %} 
<div class="row">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link {% if index %}active{% endif %}" href="{% url 'posts:index' %}">
                  Все авторы
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if follow %}active{% endif %}" href="/follow">
                Избранные авторы
            </a>
        </li>
    </ul>
</div>
{% endif %}

yatube/templates/includes/post_item.html
<div class="card mb-3 mt-1 shadow-sm">

  {% load thumbnail %}
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
  <img class="card-img" src="{{ im.url }}" />
  {% endthumbnail %}
  <div class="card-body">
    <p class="card-text">
      <a name="post_{{ post.id }}" href="{% url 'posts:profile' post.author.username %}">
        <strong class="d-block text-gray-dark">@{{ post.author }}</strong>
      </a>
      {{ post.text|linebreaksbr }}
    </p>

    {% if post.group %}
    <a class="card-link muted" href="{% url 'posts:group_posts' post.group.slug %}">
      <strong class="d-block text-gray-dark">#{{ post.group.title }}</strong>
    </a>
    {% endif %}

    <div class="d-flex justify-content-between align-items-center">
      <div class="btn-group">
        {% if post.comments.exists %}
        <div>
          Комментариев: {{ post.comments.count }}
        </div>
        {% endif %}
        <a class="btn btn-sm btn-primary" href="{% url 'posts:post_view' post.author.username post.id %}" role="button">
          Добавить комментарий
        </a>

        {% if user == post.author %}
        <a class="btn btn-sm btn-info" href="{% url 'posts:post_edit' post.author.username post.id %}" role="button">
          Редактировать
        </a>
        {% endif %}
      </div>

      <small class="text-muted">{{ post.pub_date }}</small>
    </div>
  </div>
</div>

yatube/templates/includes/user_card.html
<div class="col-md-3 mb-3 mt-1">
    <div class="card">
        <div class="card-body">
            <div class="h2">
                {{ user_profile.get_full_name }}
            </div>
            <div class="h3 text-muted">
                <a href="/{{ user_profile.username }}/"><strong class="d-block text-gray-dark">@{{ user_profile.username}}</strong></a>
            </div>
        </div>
        <li class="list-group-item">
            {% if following %}
            <a class="btn btn-lg btn-light" 
                    href="{% url 'posts:profile_unfollow' user_profile.username %}" role="button"> 
                    Отписаться 
            </a> 
            {% else %}
            <a class="btn btn-lg btn-primary" 
                    href="{% url 'posts:profile_follow' user_profile.username %}" role="button">
            Подписаться 
            </a>
            {% endif %}
        </li>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                <div class="h6 text-muted">
                    Подписчиков: {{ user_profile.following.count }} <br />
                    Подписан: {{ user_profile.follower.count }}
                </div>
            </li>
            <li class="list-group-item">
                <div class="h6 text-muted">
                    Записей: {{ user_profile.posts.count }}
                </div>
            </li>
        </ul>
    </div>
</div>