yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path("", views.index, name="index"),
    path("follow/", views.follow_index, name="follow_index"),
    path("group/<slug:slug>/", views.group_posts, name="group_posts"),
    path("new/", views.new_post, name="new_post"),
    path('<str:username>/', views.profile, name='profile'),
    path('<str:username>/<int:post_id>/', views.post_view, name='post_view'),
    path('<str:username>/<int:post_id>/edit/', views.post_edit,
         name='post_edit'),
    path("<str:username>/<int:post_id>/comment/", views.add_comment,
         name="add_comment"),
    path("<str:username>/follow/", views.profile_follow,
         name="profile_follow"),
    path("<str:username>/unfollow/", views.profile_unfollow,
         name="profile_unfollow"),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("posts.urls", namespace='app_posts')),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = "posts.views.page_not_found"
handler500 = "posts.views.server_error"

# if settings.DEBUG:
#     urlpatterns += static(
#         settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#     urlpatterns += static(
#         settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     import debug_toolbar
#     urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

# urlpatterns += [re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT,}),]
# urlpatterns += [re_path(r'^static/(?P<path>.*)$', serve, {'document_root':settings.STATIC_ROOT}),]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Post(models.Model):
    text = models.TextField(verbose_name="Комментарий")
    pub_date = models.DateTimeField("Дата публикации",
                                    auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name="posts", verbose_name="Автор")
    group = models.ForeignKey(
        "Group", on_delete=models.SET_NULL,
        related_name="posts",
        blank=True,
        null=True,
        verbose_name="Группа")
    image = models.ImageField(
        upload_to='posts/',
        blank=True,
        null=True,
        verbose_name="Изображение")

    class Meta:
        ordering = ["-pub_date"]

    def __str__(self):
        return self.text[:15]


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             related_name='comments', null=True,
                             verbose_name="Пост")
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name="comments", null=True,
                               verbose_name="Автор")
    text = models.TextField(verbose_name="Текст")
    created = models.DateTimeField(auto_now_add=True)


class Follow(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name="follower",
                             verbose_name="Подписчик")
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name="following",
                               verbose_name="Блогер")

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'], name='unique_follow')
        ]

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("text", "group", "image")
        help_texts = {
            "text": 'Введите Ваш комментарий',
            "group": 'Выберите группу',
            "image": 'Выберите картинку'
        }
        error_messages = {
            'text': {
                'required': "Заполните комментарий",
            },
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("text",)

yatube/posts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post

COUNT_POSTS = 10
User = get_user_model()


def index(request):
    posts = Post.objects.all()
    paginator = Paginator(posts, COUNT_POSTS)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, 'posts/index.html', {'page': page})


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    paginator = Paginator(posts, COUNT_POSTS)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, "group.html", {"group": group, "page": page})


@login_required
def new_post(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.save()
        return redirect("posts:index")
    return render(
        request, "posts/new_post.html",
        {"form": form, "is_new": True})


def profile(request, username):
    user_profile = get_object_or_404(User, username=username)
    paginator = Paginator(user_profile.posts.all(), COUNT_POSTS)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    following = (request.user.is_authenticated and Follow.objects.filter(
        user__username=request.user,
        author=user_profile).exists())
    return render(
        request, 'posts/profile.html',
        {'page': page, 'user_profile': user_profile,
         'following': following})


def post_view(request, username, post_id):
    post = get_object_or_404(Post, id=post_id, author__username=username)
    user_profile = post.author
    comments = post.comments.all()
    form = CommentForm()
    return render(
        request, 'posts/post.html',
        {'post': post, 'user_profile': user_profile, 'form': form,
         'comments': comments})


@login_required
def post_edit(request, username, post_id):
    post = get_object_or_404(Post, id=post_id, author__username=username)
    if request.user != post.author:
        return redirect('posts:post_view', username, post_id)
    form = PostForm(
        request.POST or None, files=request.FILES or None, instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_view', username, post_id)
    return render(
        request, 'posts/new_post.html',
        {"form": form, "post": post, "is_new": False})


def page_not_found(request, exception):
    return render(
        request,
        "misc/404.html",
        {"path": request.path},
        status=404
    )


def server_error(request):
    return render(request, "misc/500.html", status=500)


@login_required
def add_comment(request, username, post_id):
    post = get_object_or_404(Post, author__username=username, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_view', username, post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(post_list, COUNT_POSTS)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(
        request,
        "posts/follow.html",
        {'page': page, 'paginator': paginator}
    )


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(author=author, user=request.user).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/comments.html
{% load user_filters %}
{% if user.is_authenticated %}
<div class="card my-4">
    <form action="{% url 'posts:add_comment' post.author.username post.id %}" method="post">
        {% csrf_token %}
        <h5 class="card-header">Добавить комментарий:</h5>
        <div class="card-body">
            <div class="form-group">
                {{ form.text|addclass:"form-control" }}
            </div>
            <button type="submit" class="btn btn-primary">Отправить</button>
        </div>
    </form>
</div>
{% endif %}

{% for item in post.comments.all %}
<div class="media card mb-4">
    <div class="media-body card-body">
        <h5 class="mt-0">
            <a href="{% url 'posts:profile' item.author.username %}"
               name="comment_{{ item.id }}">
                {{ item.author.username }}
            </a>
        </h5>
        <p>{{ item.text | linebreaksbr }}</p>
    </div>
</div>
{% endfor %}

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% block title %}Последние обновления{% endblock %}
{% block header %}Последние обновления на сайте{% endblock %}
{% block content %}
    {% for post in page %}
        {% include "includes/post_item.html" with post=post %}
    {% endfor %}

{% if page.has_other_pages %}
    {% include "paginator.html" with items=page paginator=paginator%}
{% endif %}

{% endblock %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% block title %}Последние обновления{% endblock %}
{% block header %}Последние обновления на сайте{% endblock %}
{% load cache %}
{% block content %}

{% include "includes/menu.html" with index=True %}

{% cache 20 index_page %}
{% for post in page %}
    {% include "includes/post_item.html" with post=post %}
{% endfor %}
{% endcache %}

{% if page.has_other_pages %}
{% include "paginator.html" with items=page paginator=paginator%}
{% endif %}

{% endblock %}

yatube/templates/posts/new_post.html
{% extends "base.html" %}
{% block title %}{{ is_new|yesno:"Новый пост,Редактирование" }}{% endblock %}
{% block content %}
{% load user_filters %}

<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            
            <div class="card-header">
                {{ is_new|yesno:"Новый пост,Редактировать" }}
                </div>
            <div class="card-body">
            
                    {% for error in form.errors.values %}
                    <div class="alert alert-danger" role="alert">
                        {{ error }}
                    </div>
                    {% endfor %}

                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}

                        {% for field in form %}
                        <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{%endif %}>
                            <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                            <div class="col-md-6">
                                {{ field }}
                                {% if field.help_text %}
                                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{field.help_text|safe }}</small>
                                {% endif %}
                            </div>
                        </div>
                        {% endfor %}

                        <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">
                                {{ is_new|yesno:"Создать,Сохранить" }}
                            </button>
                        </div>
                    </form>
                </div> 
            </div> 
        </div> 
    </div> 
{% endblock %}

yatube/templates/posts/post.html
{% extends "base.html" %}
{% block title %}Пост пользователся {{ user_profile.username }}{% endblock %}
{% block content %}

<main role="main" class="container">
    <div class="row">
        {% include "includes/user_card.html" %}

        <div class="col-md-9">

            {% include "includes/post_item.html" with post=post %}
            {% include "posts/comments.html" %}
        </div>
    </div>
</main>

{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% block title %}Пользователь {{ user_profile.username }}{% endblock %}
{% block content %}
{% load user_filters %}

<main role="main" class="container">
    <div class="row">
        {% include "includes/user_card.html" %}

        <div class="col-md-9">
            {% for post in page %}
                {% include "includes/post_item.html" with post=post %}
            {% endfor %}

            {% if page.has_other_pages %}
                {% include "paginator.html" with items=page paginator=paginator%}
            {% endif %}

        </div>
    </div>
</main>

{% endblock %}